name: STORM
version: 1
author: eXioStorm
main: com.exiostorm.storm.main.Storm
description: And it\'s windy weather\, boys, stormy weather\, boys\nWhen the wind blows\, we're all together\, boys;\nBlow ye winds westerly\, blow ye winds\, blow\nJolly sou\'wester\, boys\, steady she goes
api-version: 1.13
commands:
    stormtest:
       description: a test command
       usage: /stormtest
       permission: storm.test
       permission-message: You must not be Storm! please elevate your permissions!
